stages:
  - build
  - test
  - package
image: dr.test.x/dust:3-arch-install

build:
  stage: build
  script:
    - id
    - . $HOME/.cargo/env
    - rustup run nightly cargo build --release --all-targets

test:
  stage: test
  script:
    - . $HOME/.cargo/env
    - ci/bootstrap.sh

release:
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release of DUST - $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
