[workspace]
members = [
    './ast',
    './either',
    './error',
    './main',
    './parse',
]
[patch.crates-io.ast]
path = './ast'

[patch.crates-io.either]
path = './either'

[patch.crates-io.error]
path = './error'

[patch.crates-io.main]
path = './main'

[patch.crates-io.parse]
path = './parse'
