[workspace]
members = [
    './app_error',
    './error',
    './main_drive',
    './parser_1',
    './vm-core',
    './vm-exec',
]
[patch.crates-io.app_error]
path = './app_error'

[patch.crates-io.error]
path = './error'

[patch.crates-io.main_drive]
path = './main_drive'

[patch.crates-io.parser_1]
path = './parser_1'

[patch.crates-io.vm-core]
path = './vm-core'

[patch.crates-io.vm-exec]
path = './vm-exec'
